- name: "install {{component}}" #i am creating one variable in that passing values
  hosts: localhost
  connection: local
  vars_files:
  - variables-{{env}}.yaml
  become: yes
  roles:
  - "{{component}}"
  